version: '{build}'

environment:
  APPVEYOR: 1
  DEPLOY: 0

  matrix:
    # MSVC x86
    - PLATFORM: amd64_x86
      QTDIR: C:\Qt\5.7\msvc2015
      MAKE: nmake
      MAKEFILES: NMake Makefiles
      DEPLOY: 1

init:
  - git config --global core.autocrlf input
  - set PATH=%QTDIR%\bin;%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %PLATFORM%

build_script:
  - cd server
  - mkdir build
  - cd build
  - cmake .. -G "%MAKEFILES%" -DCMAKE_BUILD_TYPE=Release
  - nmake
  - cd ..
  - copy "build\gui\VN Streamer.exe" "dist\VN Streamer.exe"

artifacts:
- path: server\dist\
  name: Server
  type: zip

deploy:
  - provider: GitHub
    tag: nightly
    release: Nightly
    draft: false
    prerelease: true
    force_update: true
    artifact: Server
    description: |
      Nightly automated builds from the develop branch.
      Automatically uploaded by AppVeyor, **use at your own risk**!
      **Head:** $(APPVEYOR_REPO_COMMIT)
      **Date:** $(APPVEYOR_REPO_COMMIT_TIMESTAMP)
    auth_token:
      secure: mUYQ72KBJUaYr5Bhy2HkBkEY13Q7k27Q7IRmOGXfTOq7YnXUS9PikETcZvzCfiVu
    on:
#      branch: master
      DEPLOY: 1